apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: grafana
  labels:
    app: grafana
spec:
  type: NodePort  # Change the type to NodePort
  ports:
  - name: service
    port: 3000
    targetPort: 3000
    nodePort: 32000  # Specify the NodePort value (choose a value within the valid range)
    protocol: TCP
  selector:
    app: grafana
